### ISSUE TITLE
upload generic API large file fails silently with PayloadTooLargeError

### ISSUE THREAD

**Issue by n2ygk** [awslabs/aws-api-gateway-developer-portal#296]
Trying to add a generic API:

1. Select the JSON file.
2. Click Upload

Results in a greyed out upload UI and no message.

Viewing in Javascript console shows that the attempt to `POST /prod/admin/catalog/visibility` fails with an uncaught 413 status:

<html lang="en">
<head>
<pre>PayloadTooLargeError: request entity too large<br> &nbsp; &nbsp;at IncomingMessage.onData (/var/task/node_modules/raw-body/index.js:246:12)<br> &nbsp; &nbsp;at emitOne (events.js:116:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:211:7)<br> &nbsp; &nbsp;at addChunk (_stream_readable.js:263:12)<br> &nbsp; &nbsp;at readableAddChunk (_stream_readable.js:250:11)<br> &nbsp; &nbsp;at IncomingMessage.Readable.push (_stream_readable.js:208:10)<br> &nbsp; &nbsp;at HTTPParser.parserOnBody (_http_common.js:139:22)</pre>
</html>

I can provide a 330K example file if needed, but I expect any large file upload will break it.

**Comment by eegnoc** [comment]
same issue for me. File size is 167kb, will be 350kb when done.

did some research and then reduced the file size to be just under 128kb and it loads just fine. so that eliminates a badly formatted file (mostly), or corrupt file.

did some more research and I undertsand the AWS API gateway has a 128kb limit when using websockets. Is limit in play here? have I mucked up something fundamential.

Appreciate any advice.
