### ISSUE TITLE
Unable to import module 'index': Error

### ISSUE THREAD

**Issue by jayyousi** [awslabs/aws-api-gateway-developer-portal#53]
I'm seeing this error in cloudwatch when clicking on the API's link after deploying the developer portal

START RequestId: 515f2f43-5e26-11e7-8c2d-af9c53f4a702 Version: $LATEST

Unable to import module 'index': Error at Function.Module._resolveFilename (module.js:325:15) at Function.Module._load (module.js:276:25) at Module.require (module.js:353:17) at require (internal/module.js:12:17) at Object.<anonymous> (/var/task/express-server.js:10:29) at Module._compile (module.js:409:26) at Object.Module._extensions..js (module.js:416:10) at Modu
Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/express-server.js:10:29)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)

**Comment by kahouieong** [comment]
Did you modify the portal before you deploy? Also, please provide your environment information.

**Comment by jayyousi** [comment]
I've cloned the repository locally and ran the command `npm run win-setup`

npm -v
5.0.4

node -v
v8.1.2

**Comment by zachdb86** [comment]
Please look at issue #54 for solution.

**Comment by bejos** [comment]
Fixed in https://github.com/awslabs/aws-api-gateway-developer-portal/pull/61
